"""Edit table memes, add column format_file

Revision ID: 527059a7410d
Revises: 687ce5f99628
Create Date: 2024-06-21 01:32:58.995423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527059a7410d'
down_revision: Union[str, None] = '687ce5f99628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('format_file', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memes', 'format_file')
    # ### end Alembic commands ###
