"""Edit table memes, rename column format_file on file_name

Revision ID: b1cc387dbdd6
Revises: 527059a7410d
Create Date: 2024-06-21 01:45:19.945082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1cc387dbdd6'
down_revision: Union[str, None] = '527059a7410d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('file_name', sa.String(), nullable=False))
    op.drop_column('memes', 'format_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('format_file', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('memes', 'file_name')
    # ### end Alembic commands ###
