version: '3.7'
services:
  db:
    image: postgres:15
    container_name: booking_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: booking_redis
    ports:
      - 6379:6379

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./storage/minio:/data
    command: server /data
    env_file:
      - .env-non-dev

  booking:
    image: booking_image
    build:
      context: .
    container_name: booking_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
      - s3
    command: ["/booking/docker/app.sh"]
    ports:
      - 8080:8000

  volumes:
    postgresdata: